package com.example.cybersecurity.service;

import com.mailjet.client.ClientOptions;
import com.mailjet.client.MailjetClient;
import com.mailjet.client.MailjetRequest;
import com.mailjet.client.MailjetResponse;
import com.mailjet.client.resource.Emailv31;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Base64;

@Service
public class MailjetEmailService {

    @Value("${mailjet.api.key}")
    private String apiKey;

    @Value("${mailjet.secret.key}")
    private String secretKey;

    @Value("${mailjet.from.email}")
    private String fromEmail;

    private MailjetClient getClient() {
        ClientOptions options = ClientOptions.builder()
                .apiKey(apiKey)
                .apiSecretKey(secretKey)
                .build();
        return new MailjetClient(options);
    }

    @Async
    public void sendIncidentSolvedEmail(String toEmail, String subject, String body) {
        try {
            MailjetClient client = getClient();
            
            MailjetRequest request = new MailjetRequest(Emailv31.resource)
                    .property(Emailv31.MESSAGES, new JSONArray()
                        .put(new JSONObject()
                            .put(Emailv31.Message.FROM, new JSONObject()
                                .put("Email", fromEmail)
                                .put("Name", "Cyber Security System"))
                            .put(Emailv31.Message.TO, new JSONArray()
                                .put(new JSONObject()
                                    .put("Email", toEmail)))
                            .put(Emailv31.Message.SUBJECT, subject)
                            .put(Emailv31.Message.HTMLPART, body)));
            
            MailjetResponse response = client.post(request);
            System.out.println("Email sent to: " + toEmail + " - Status: " + response.getStatus());
            
        } catch (Exception e) {
            System.err.println("Failed to send email to: " + toEmail);
            e.printStackTrace();
        }
    }

    public void sendPdfReportEmail(String toEmail, String generatedBy, byte[] pdfBytes) {
        String subject = "Cybersecurity Incident PDF Report";
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        
        String body = String.format("""
            <h2>PDF Report Generated</h2>
            <p>Your Cybersecurity Incident PDF Report has been generated.</p>
            <p><strong>Generated by:</strong> %s</p>
            <p><strong>Date:</strong> %s</p>
            <p>PDF report is attached to this email.</p>
            <br/>
            <p>Regards,<br/>Cyber Security Incident Management System</p>
            """,
            generatedBy,
            timestamp
        );
        
        try {
            MailjetClient client = getClient();
            
            // Encode PDF to Base64
            String encodedPdf = Base64.getEncoder().withoutPadding().encodeToString(pdfBytes);
            
            MailjetRequest request = new MailjetRequest(Emailv31.resource)
                    .property(Emailv31.MESSAGES, new JSONArray()
                        .put(new JSONObject()
                            .put(Emailv31.Message.FROM, new JSONObject()
                                .put("Email", fromEmail)
                                .put("Name", "Cyber Security System"))
                            .put(Emailv31.Message.TO, new JSONArray()
                                .put(new JSONObject()
                                    .put("Email", toEmail)))
                            .put(Emailv31.Message.SUBJECT, subject)
                            .put(Emailv31.Message.HTMLPART, body)
                            .put(Emailv31.Message.ATTACHMENTS, new JSONArray()
                                .put(new JSONObject()
                                    .put("ContentType", "application/pdf")
                                    .put("Filename", "incident-report.pdf")
                                    .put("Base64Content", encodedPdf)))));
            
            MailjetResponse response = client.post(request);
            System.out.println("PDF report email sent to: " + toEmail + " - Status: " + response.getStatus());
            
        } catch (Exception e) {
            System.err.println("Failed to send PDF report email to: " + toEmail);
            e.printStackTrace();
        }
    }
}