package com.example.cybersecurity.service;

import com.mailjet.client.ClientOptions;
import com.mailjet.client.MailjetClient;
import com.mailjet.client.MailjetRequest;
import com.mailjet.client.MailjetResponse;
import com.mailjet.client.resource.Emailv31;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

@Service
public class MailjetEmailService {

    @Value("${mailjet.api.key}")
    private String apiKey;

    @Value("${mailjet.secret.key}")
    private String secretKey;

    @Value("${mailjet.from.email}")
    private String fromEmail;

    private MailjetClient getClient() {
        ClientOptions options = ClientOptions.builder()
                .apiKey(apiKey)
                .apiSecretKey(secretKey)
                .build();
        return new MailjetClient(options);
    }

    @Async
    public void sendIncidentSolvedEmail(String toEmail, String subject, String body) {
        try {
            MailjetClient client = getClient();
            
            MailjetRequest request = new MailjetRequest(Emailv31.resource)
                    .property(Emailv31.MESSAGES, new JSONArray()
                        .put(new JSONObject()
                            .put(Emailv31.Message.FROM, new JSONObject()
                                .put("Email", fromEmail)
                                .put("Name", "Cyber Security System"))
                            .put(Emailv31.Message.TO, new JSONArray()
                                .put(new JSONObject()
                                    .put("Email", toEmail)))
                            .put(Emailv31.Message.SUBJECT, subject)
                            .put(Emailv31.Message.HTMLPART, body)));
            
            MailjetResponse response = client.post(request);
            System.out.println("Email sent to: " + toEmail + " - Status: " + response.getStatus());
            
        } catch (Exception e) {
            System.err.println("Failed to send email to: " + toEmail);
            e.printStackTrace();
        }
    }

    @Async
    public void sendPdfReportEmail(String toEmail, String generatedBy) {
        String subject = "Cybersecurity Incident PDF Report";
        String body = String.format("""
            <h2>PDF Report Generated</h2>
            <p>Your Cybersecurity Incident PDF Report has been generated.</p>
            <p><strong>Generated by:</strong> %s</p>
            <p><strong>Date:</strong> %s</p>
            <p>You can download the report using the Download PDF button in the system.</p>
            """,
            generatedBy,
            java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
        );
        
        sendIncidentSolvedEmail(toEmail, subject, body);
    }
}