package com.example.cybersecurity.service;

import com.example.cybersecurity.model.Incident;
import com.example.cybersecurity.model.User;
import com.example.cybersecurity.repository.UserRepository;
import com.resend.Resend;
import com.resend.services.emails.model.CreateEmailOptions;
import com.resend.services.emails.model.CreateEmailResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class NotificationEmailService {

    private final UserRepository userRepository;

    @Value("${resend.api.key}")
    private String apiKey;

    @Value("${resend.from.email}")
    private String fromEmail;

    @Value("${report.recipient.email}")
    private String reportRecipientEmail;

    public NotificationEmailService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @Async
    public void sendIncidentSolvedNotification(Incident incident, String resolvedBy) {
        if (apiKey == null || apiKey.isBlank()) {
            System.out.println("Resend API key is missing. Email not sent.");
            return;
        }

        Resend resend = new Resend(apiKey);
        
        List<User> admins = userRepository.findByRole("ADMIN");
        if (admins.isEmpty()) {
            System.out.println("No admin users found.");
            return;
        }

        String subject = "Incident Solved Notification - " + safe(incident.getTitle());
        
        String createdAtText = incident.getCreatedAt() != null
                ? incident.getCreatedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                : "Unknown";

        String body = """
                <h2>Incident Solved</h2>
                <p><strong>Title:</strong> %s</p>
                <p><strong>Logged By:</strong> %s</p>
                <p><strong>Date Logged:</strong> %s</p>
                <p><strong>Assigned Role:</strong> %s</p>
                <p><strong>Resolved By:</strong> %s</p>
                <p><strong>Status:</strong> %s</p>
                <p><strong>Recommendation:</strong> %s</p>
                <br/>
                <p>Regards,<br/>Cyber Security Incident Management System</p>
                """.formatted(
                safe(incident.getTitle()),
                safe(incident.getCreatedBy()),
                createdAtText,
                safe(incident.getAssignedRole()),
                safe(resolvedBy),
                safe(incident.getStatus()),
                safe(incident.getRecommendation())
        );

        for (User admin : admins) {
            try {
                CreateEmailOptions options = CreateEmailOptions.builder()
                        .from(fromEmail)
                        .to(admin.getEmail())
                        .subject(subject)
                        .html(body)
                        .build();
                CreateEmailResponse response = resend.emails().send(options);
                System.out.println("Email sent to: " + admin.getEmail() + " - ID: " + response.getId());
            } catch (Exception e) {
                System.err.println("Failed to send to: " + admin.getEmail());
                e.printStackTrace();
            }
        }
    }

    public void sendIncidentReportPdf(byte[] pdfBytes, String generatedBy) {
        if (apiKey == null || apiKey.isBlank()) {
            System.out.println("Resend API key is missing. Email not sent.");
            return;
        }

        Resend resend = new Resend(apiKey);
        
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        
        String body = """
                <h2>PDF Report Ready</h2>
                <p>Your Cybersecurity Incident PDF Report has been generated.</p>
                <p><strong>Generated by:</strong> %s</p>
                <p><strong>Generated on:</strong> %s</p>
                <p>You can download the report using the Download PDF button in the system.</p>
                <br/>
                <p>Regards,<br/>Cyber Security Incident Management System</p>
                """.formatted(
                generatedBy == null || generatedBy.isBlank() ? "Unknown" : generatedBy,
                timestamp
        );

        try {
            CreateEmailOptions options = CreateEmailOptions.builder()
                    .from(fromEmail)
                    .to(reportRecipientEmail)
                    .subject("Cybersecurity Incident PDF Report - Ready for Download")
                    .html(body)
                    .build();
            CreateEmailResponse response = resend.emails().send(options);
            System.out.println("PDF report email sent to: " + reportRecipientEmail + " - ID: " + response.getId());
        } catch (Exception e) {
            System.err.println("Failed to send PDF report email to: " + reportRecipientEmail);
            e.printStackTrace();
        }
    }

    private String safe(String value) {
        return value == null || value.isBlank() ? "N/A" : value;
    }
}