package com.example.cybersecurity.service;

import com.example.cybersecurity.model.Incident;
import com.example.cybersecurity.model.User;
import com.example.cybersecurity.repository.UserRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class NotificationEmailService {

    private final JavaMailSender mailSender;
    private final UserRepository userRepository;

    @Value("${spring.mail.username}")
    private String fromEmail;

    @Value("${report.recipient.email}")
    private String reportRecipientEmail;

    public NotificationEmailService(JavaMailSender mailSender, UserRepository userRepository) {
        this.mailSender = mailSender;
        this.userRepository = userRepository;
    }

    @Async
    public void sendIncidentSolvedNotification(Incident incident, String resolvedBy) {
        List<User> admins = userRepository.findByRole("ADMIN");
        
        if (admins.isEmpty()) return;

        String body = String.format("""
                Incident: %s
                Status: SOLVED
                Resolved By: %s
                Date: %s
                """,
                incident.getTitle(),
                resolvedBy,
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
        );

        for (User admin : admins) {
            try {
                SimpleMailMessage message = new SimpleMailMessage();
                message.setFrom(fromEmail);
                message.setTo(admin.getEmail());
                message.setSubject("Incident Solved - " + incident.getTitle());
                message.setText(body);
                mailSender.send(message);
            } catch (Exception e) {
                System.err.println("Failed to send email to: " + admin.getEmail());
            }
        }
    }

    public void sendIncidentReportPdf(byte[] pdfBytes, String generatedBy) {
        try {
            String body = String.format("""
                    PDF Report Generated
                    
                    Generated by: %s
                    Date: %s
                    """,
                    generatedBy,
                    LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
            );

            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(reportRecipientEmail);
            message.setSubject("Cybersecurity Incident PDF Report");
            message.setText(body);
            mailSender.send(message);
        } catch (Exception e) {
            System.err.println("Failed to send PDF report email");
        }
    }
}