spring.datasource.url=jdbc:mysql://localhost:3306/cyber_incident_db?useSSL=false&serverTimezone=Africa/Johannesburg&allowPublicKeyRetrieval=true
spring.datasource.username=faith
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cyberincident.managment@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
report.recipient.email=${REPORT_RECIPIENT_EMAIL}

openai.api.key=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
openai.model=gpt-4o-mini

